#!/bin/sh

set -e

rm -f system

( cd input-generators/syspy ; ./$1 ; mv system ../.. ; cd ../.. )

# ( cd input-generators/qs/cubicMPGrid; ./h $3 > out; mv WeightedQ ../../../ ) 
# ( cd input-generators/qs/directionalQs; ./mk; ./h; mv WeightedQ ../../../ ) 

./mk

./randomQs $3
# ./regularQs $3

./h $2
./pd $2 $4

./g.py DOS*
